### ISSUE TITLE
[Help Wanted] Type 불일치

### ISSUE THREAD

**Issue by DONOTINTO** [DONOTINTO/Login_SpotifyUI#47]
<img width="900" alt="스크린샷 2023-05-17 오후 10 24 14" src="https://github.com/DONOTINTO/Login_SpotifyUI/assets/123792519/da784bb9-3bec-4731-acc6-bc0f3f283f44">  

</br>

register.playList.filter를 통해 music의 title과 searchText가 일치한 경우만 filteredData에 넣으려했습니다.
하지만 리턴값이 LazyFilterSequence<List<Music>> 이라는 LazyFilterSequence라는 타입이 붙으면서 값을 넣을 수 없습니다.

**Comment by keenkim1202** [comment]
기존 코드를 유지하는 방향으로 수정하면 아래와 같이 사용할 수 있습니다.
```swift
var filteredData: [Music]?

if searchText.isEmpty {
    filteredData = Array(register.playList)
} else {
    let filtered = register.playList.filter{ $0.title.lowercased() == searchText.lowercased() }
    filteredData = Array(filtered)
}
```

1) 
보편적으로는 Realm객체로부터 데이터를 가져와 `filter()` 메서드에 query문자열을 인자로 넣어 filtering을 합니다.  
(Swift언어에 존재하는 `filter()`메서드가 아닌 Realm 라이브러리에서 제공하는 `filter()` 메서드)
```swift
realm.objects(SomeData.self).filter("title contains '\(searchText)'")
```

2)
`.where()` 메서드를 활용하여 원하는 결과를 걸러낼 수도 있습니다.
```swift
let filtered = someData.where {
    $0.name.contains("abc")
}
```

- 참고 링크: [Realm Swift - filter-data](www.mongodb.com/docs/realm/sdk/swift/crud/filter-data/)
